ui: mocha-bdd
browsers:
  - name: chome
    version: 20..latest
  - name: ie
    version: 11..latest
  - name: firefox
    version: 12..latest
  - name: safari
    version: 6..latest
  - name: iphone
    version: 6.0..latest
  - name: android
    version: 4.4..latest
